# Generated by Django 5.2.7 on 2025-10-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(help_text='ID from external API', unique=True)),
                ('name', models.CharField(help_text='Discount name', max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage', max_digits=5)),
                ('description', models.TextField(blank=True, help_text='Discount description')),
                ('valid_from', models.DateTimeField(help_text='Discount valid from date and time')),
                ('valid_to', models.DateTimeField(help_text='Discount valid to date and time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'ordering': ['-valid_to'],
            },
        ),
    ]
