# Generated by Django 5.2.7 on 2025-10-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='external_id',
            field=models.CharField(help_text='ID from external API', max_length=255, unique=True),
        ),
    ]
