service: web-api

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs22.x
  region: eu-central-1
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_DATABASE: ${env:DB_DATABASE}

functions:
  main:
    handler: dist/lambda.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any